spring:
  datasource:
    url: "jdbc:postgresql://postgres:5432/trees4cities"
    username: postgres
    password: baguga123
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migrations
